//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDiem
    {
        public int MaCTDiem { get; set; }
        public Nullable<int> MaDiem { get; set; }
        public Nullable<double> Diem15Phut { get; set; }
        public Nullable<double> Diem1Tiet { get; set; }
        public Nullable<double> DiemTB { get; set; }
    
        public virtual Diem Diem { get; set; }
    }
}
