//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Diem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diem()
        {
            this.CTDiems = new HashSet<CTDiem>();
        }

        public int MaDiem { get; set; }
        public Nullable<int> MaHocSinh { get; set; }
        public Nullable<int> MaHocKy { get; set; }
        public Nullable<int> MaMon { get; set; }
        public string DiemTB { get; set; }
        [NotMapped]
        public string DeletedCTBangDiem { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDiem> CTDiems { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
